version: 0.0
os: linux
files:
  - source: .
    destination: /opt/app
hooks:
  ApplicationStop:
    - location: bin/stop
      timeout: 300
  AfterInstall:
    - location: bin/unpack
  ApplicationStart:
    - location: bin/migrate
      runas: ec2-user
      timeout: 300
    - location: bin/start
      timeout: 3600
  ValidateService:
    - location: bin/healthz
      timeout: 3600
