version: 0.2

env:
  variables:
    MIX_ENV: "prod"

phases:
  install:
    commands:
      - chmod +x bin/build
      - bin/build install
  pre_build:
    commands:
      - bin/build pre_build
  build:
    commands:
      - bin/build build
  post_build:
    commands:
      - bin/build post_build

artifacts:
  files:
    - templates/infra.yml
    - templates/production.conf
    - bin/unpack
    - bin/stop
    - bin/migrate
    - bin/start
    - bin/healthz
  discard-paths: no
  secondary-artifacts:
    engine:
      files:
        - engine.tar.gz
        - engine.appspec.yml
      discard-paths: no
    web:
      files:
        - web.tar.gz
        - web.appspec.yml
      discard-paths: no

